# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Pull the docker image
      - name: Pull docker image 
        run: docker pull adnrv/texlive:full
      
      # Build the tex file
      - name: Build resume_cv.pdf 
        run: docker run --rm --user="$(id -u):$(id -g)" -v "$GITHUB_WORKSPACE":/home adnrv/texlive:full xelatex resume_cv.tex
 
      # Upload the resume as artifact
      #- name: Upload the resume as artifact
      #  uses: actions/upload-artifact@v3.1.1
      #  with:
      #  # Artifact name
      #    name: resume
      #    # A file, directory or wildcard pattern that describes what to upload
      #    path: ${{ github.workspace }}/resume_cv.pdf
      #    if-no-files-found: error
      
      - name: Upload pdf to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/resume_cv.pdf
          asset_name: resume.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest build of the resume"
